# Generated by Django 4.2.16 on 2026-09-28 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('facility_type', models.CharField(choices=[('MAIN_ADMIN', 'Main Admin'), ('LAB', 'Lab'), ('FACTORY', 'Factory'), ('HOSTEL', 'Hostel'), ('CANTEEN', 'Canteen'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('area_sqft', models.FloatField(default=0.0)),
                ('floors', models.IntegerField(default=1)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'Maintenance')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tenant_id', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmartMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_id', models.CharField(max_length=100, unique=True)),
                ('meter_type', models.CharField(choices=[('MAIN', 'Main'), ('SUB', 'Sub'), ('SOLAR', 'Solar'), ('BATTERY', 'Battery'), ('EV', 'EV')], default='MAIN', max_length=20)),
                ('make', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('rated_capacity_kw', models.FloatField(default=0.0)),
                ('installed_date', models.DateField(blank=True, null=True)),
                ('last_calibrated', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('FAULT', 'Fault')], default='ACTIVE', max_length=20)),
                ('connection_type', models.CharField(choices=[('1-PHASE', '1-Phase'), ('3-PHASE', '3-Phase')], default='3-PHASE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='facilities.facility')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='facility',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='facilities.organization'),
        ),
    ]
