# Generated by Django 4.2.16 on 2026-09-29 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('WARNING', 'Warning'), ('INFO', 'Info')], default='WARNING', max_length=20)),
                ('category', models.CharField(choices=[('PEAK_DEMAND', 'Peak Demand Risk'), ('SUB_METER', 'Sub-meter Anomaly'), ('RENEWABLE', 'Renewable / BESS'), ('POWER_QUALITY', 'Power Quality / THD')], default='PEAK_DEMAND', max_length=30)),
                ('meter_id', models.CharField(blank=True, max_length=100, null=True)),
                ('observed_val', models.CharField(blank=True, max_length=100, null=True)),
                ('limit_val', models.CharField(blank=True, max_length=100, null=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='facilities.facility')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
