# Generated by Django 4.2.16 on 2026-09-28 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('kwh_consumed', models.FloatField(default=0.0)),
                ('kw_demand', models.FloatField(default=0.0)),
                ('kvar_reactive', models.FloatField(default=0.0)),
                ('power_factor', models.FloatField(default=1.0)),
                ('voltage_avg', models.FloatField(default=230.0)),
                ('current_avg', models.FloatField(default=0.0)),
                ('frequency', models.FloatField(default=50.0)),
                ('thd_voltage', models.FloatField(default=2.0)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='facilities.smartmeter')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['meter', 'timestamp'], name='energy_ener_meter_i_63a364_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyEnergyAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_kwh', models.FloatField(default=0.0)),
                ('peak_kw', models.FloatField(default=0.0)),
                ('avg_kw', models.FloatField(default=0.0)),
                ('min_kw', models.FloatField(default=0.0)),
                ('avg_power_factor', models.FloatField(default=1.0)),
                ('off_peak_kwh', models.FloatField(default=0.0)),
                ('on_peak_kwh', models.FloatField(default=0.0)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_aggregates', to='facilities.smartmeter')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('meter', 'date')},
            },
        ),
    ]
