# Generated by Django 4.2.16 on 2026-09-29 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BESSAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('capacity_kwh', models.FloatField(default=1000.0)),
                ('current_charge_kwh', models.FloatField(default=820.0)),
                ('state_of_charge_pct', models.FloatField(default=82.0)),
                ('discharging_rate_kw', models.FloatField(default=200.0)),
                ('temperature_c', models.FloatField(default=28.4)),
                ('health_pct', models.FloatField(default=99.1)),
                ('status', models.CharField(default='DISCHARGING', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SolarAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('capacity_kw', models.FloatField(default=350.0)),
                ('current_generation_kw', models.FloatField(default=280.5)),
                ('daily_yield_kwh', models.FloatField(default=1420.0)),
                ('efficiency_pct', models.FloatField(default=98.4)),
                ('status', models.CharField(default='ONLINE', max_length=20)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solar_assets', to='facilities.facility')),
            ],
        ),
    ]
