# Generated by Django 4.2.16 on 2026-09-29 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Standard Commercial Tier', max_length=100)),
                ('tier1_rate', models.FloatField(default=5.5, help_text='0-100 kWh Base Slab Rate')),
                ('tier2_rate', models.FloatField(default=6.8, help_text='101-500 kWh Intermediate Slab Rate')),
                ('tier3_rate', models.FloatField(default=8.5, help_text='501+ kWh Commercial Standard Rate')),
                ('peak_surcharge_rate', models.FloatField(default=10.5, help_text='13:00-17:00 Peak Hour Tariff Rate')),
                ('fixed_charge_monthly', models.FloatField(default=8500.0)),
                ('tax_percentage', models.FloatField(default=12.0)),
                ('solar_credit_rate', models.FloatField(default=4.5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UtilityBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_period', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_kwh', models.FloatField(default=0.0)),
                ('energy_charges', models.FloatField(default=0.0)),
                ('fixed_charges', models.FloatField(default=0.0)),
                ('tax_amount', models.FloatField(default=0.0)),
                ('renewable_credit', models.FloatField(default=0.0)),
                ('net_payable', models.FloatField(default=0.0)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('DUE', 'Due / Pending'), ('OVERDUE', 'Overdue')], default='DUE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='facilities.facility')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
