# Generated by Django 4.2.16 on 2026-09-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilitybill',
            name='is_generated',
            field=models.BooleanField(default=False),
        ),
    ]
