# Generated by Django 4.2.16 on 2026-09-29 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('energy', 'Energy Consumption & Telemetry Stream'), ('billing', 'Utility Billing & Cost Allocation Audit')], max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='facilities.facility')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
